language: c

compiler: gcc

before_script:
  - sudo apt-get update
  - sudo apt-get install -y cmake make libsdl2-*0 libsdl2-*-dev

script:
  - cmake /src
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash execute.sh
